local whichKey = require("which-key")
local language_integration = require("language_integration")
local starcraft = require("starcraft")

function create_or_open_file()
  local file = vim.fn.input("File name: ")
  local path = vim.fn.expand("%:p:h") .. "/" .. file
  vim.cmd("edit " .. path)
end

-- vim.api.nvim_del_keymap("n", "'")

whichKey.register(
  {
    ["<leader>"] = {
      t = {
        name = "Terminal",
        -- Opens a terminal on the right side of the screen
        t = { "<cmd>rightbelow vnew +terminal<CR>", "Terminal" },
        -- Opens a new terminal in a new tab
        T = { "<cmd>tabnew +terminal<CR>", "Terminal Tab" },
      },
      G = {
        name = "git",
        P = { "<cmd>Git push<CR>", "Push" },
        G = { "<cmd>Git<CR>", "Status" },
        p = { "<cmd>Git pull<CR>", "Pull" },
        C = { "<cmd>Git commit<CR>", "Commit" },
        B = { "<cmd>Git blame<CR>", "Blame" },
        L = { "<cmd>Git log<CR>", "Log" },
        l = { "<cmd>Telescope git_commits<CR>", "Log" },
      },
      ["<leader>"] = {
        name = "Source files",
        S = { "<cmd>source ~/.config/nvim/lua/snippets.lua<CR>", "Snippets" },
        L = { "<cmd>source ~/.config/nvim/lua/config.lua<CR>", "Config" },
        R = { "<cmd>source ~/.config/nvim/init.vim<CR>", "Reload" },
      },
      ["<TAB>"] = {"<C-6>", "Switch to last open buffer"},
      m = {
        name = "Starcraft",
        ["1"] = { function() starcraft.bind_buffer("1") end, "Bind Starcraft buffer #1" },
        ["2"] = { function() starcraft.bind_buffer("2") end, "Bind Starcraft buffer #2" },
        ["3"] = { function() starcraft.bind_buffer("3") end, "Bind Starcraft buffer #3" },
        ["4"] = { function() starcraft.bind_buffer("4") end, "Bind Starcraft buffer #4" },
        ["5"] = { function() starcraft.bind_buffer("5") end, "Bind Starcraft buffer #5" },
        ["6"] = { function() starcraft.bind_buffer("6") end, "Bind Starcraft buffer #6" },
        ["7"] = { function() starcraft.bind_buffer("7") end, "Bind Starcraft buffer #7" },
        ["8"] = { function() starcraft.bind_buffer("8") end, "Bind Starcraft buffer #8" },
        ["9"] = { function() starcraft.bind_buffer("9") end, "Bind Starcraft buffer #9" },
        ["0"] = { function() starcraft.bind_buffer("0") end, "Bind Starcraft buffer #10" },
      },
      ["1"] = { function() starcraft.go_to_buffer("1") end, "Go to Starcraft buffer #1" },
      ["2"] = { function() starcraft.go_to_buffer("2") end, "Go to Starcraft buffer #2" },
      ["3"] = { function() starcraft.go_to_buffer("3") end, "Go to Starcraft buffer #3" },
      ["4"] = { function() starcraft.go_to_buffer("4") end, "Go to Starcraft buffer #4" },
      ["5"] = { function() starcraft.go_to_buffer("5") end, "Go to Starcraft buffer #5" },
      ["6"] = { function() starcraft.go_to_buffer("6") end, "Go to Starcraft buffer #6" },
      ["7"] = { function() starcraft.go_to_buffer("7") end, "Go to Starcraft buffer #7" },
      ["8"] = { function() starcraft.go_to_buffer("8") end, "Go to Starcraft buffer #8" },
      ["9"] = { function() starcraft.go_to_buffer("9") end, "Go to Starcraft buffer #9" },
      ["0"] = { function() starcraft.go_to_buffer("0") end, "Go to Starcraft buffer #10" },
    },
    ["-"] = {
      name = "File Tree",
      ["-"] = {"<cmd>NERDTreeToggle<CR>", "Toggle NERDTree"},
      f = {"<cmd>NERDTreeFind<CR>", "Find file in NERDTree"},
      a = {create_or_open_file, "Create or open file"},
    },
    ["<localleader>"] = {
      name = "Language integration",
      c = { language_integration.compile, "Compile" },
      t = { language_integration.run_tests, "Run tests" },
    },
    ["<C-h>"] = { "<C-w>h", "Move to left window" },
    ["<C-j>"] = { "<C-w>j", "Move to bottom window" },
    ["<C-k>"] = { "<C-w>k", "Move to top window" },
    ["<C-l>"] = { "<C-w>l", "Move to right window" },
    ["<C-p>"] = { function() starcraft.pick_buffer() end, "Pick Starcraft buffer" },
    m = {
      name = "Starcraft",
      ["<F1>"] = { function() starcraft.bind_buffer("F1") end, "Bind Starcraft buffer F1" },
      ["<F2>"] = { function() starcraft.bind_buffer("F2") end, "Bind Starcraft buffer F2" },
      ["<F3>"] = { function() starcraft.bind_buffer("F3") end, "Bind Starcraft buffer F3" },
      ["<F4>"] = { function() starcraft.bind_buffer("F4") end, "Bind Starcraft buffer F4" },
      ["<F5>"] = { function() starcraft.bind_buffer("F5") end, "Bind Starcraft buffer F5" },
      ["<F6>"] = { function() starcraft.bind_buffer("F6") end, "Bind Starcraft buffer F6" },
      ["<F7>"] = { function() starcraft.bind_buffer("F7") end, "Bind Starcraft buffer F7" },
      ["<F8>"] = { function() starcraft.bind_buffer("F8") end, "Bind Starcraft buffer F8" },
      ["<F9>"] = { function() starcraft.bind_buffer("F9") end, "Bind Starcraft buffer F9" },
      ["<F10>"] = { function() starcraft.bind_buffer("F10") end, "Bind Starcraft buffer F10" },
      ["<F11>"] = { function() starcraft.bind_buffer("F11") end, "Bind Starcraft buffer F11" },
      ["<F12>"] = { function() starcraft.bind_buffer("F12") end, "Bind Starcraft buffer F12" },
      ["1"] = { function() starcraft.bind_buffer("1") end, "Bind Starcraft buffer #1" },
      ["2"] = { function() starcraft.bind_buffer("2") end, "Bind Starcraft buffer #2" },
      ["3"] = { function() starcraft.bind_buffer("3") end, "Bind Starcraft buffer #3" },
      ["4"] = { function() starcraft.bind_buffer("4") end, "Bind Starcraft buffer #4" },
      ["5"] = { function() starcraft.bind_buffer("5") end, "Bind Starcraft buffer #5" },
      ["6"] = { function() starcraft.bind_buffer("6") end, "Bind Starcraft buffer #6" },
      ["7"] = { function() starcraft.bind_buffer("7") end, "Bind Starcraft buffer #7" },
      ["8"] = { function() starcraft.bind_buffer("8") end, "Bind Starcraft buffer #8" },
      ["9"] = { function() starcraft.bind_buffer("9") end, "Bind Starcraft buffer #9" },
      ["0"] = { function() starcraft.bind_buffer("0") end, "Bind Starcraft buffer #10" },
      ["a"] = { function() starcraft.bind_buffer("a") end, "Bind Starcraft buffer 'a'" },
      ["b"] = { function() starcraft.bind_buffer("b") end, "Bind Starcraft buffer 'b'" },
      ["c"] = { function() starcraft.bind_buffer("c") end, "Bind Starcraft buffer 'c'" },
      ["d"] = { function() starcraft.bind_buffer("d") end, "Bind Starcraft buffer 'd'" },
      ["e"] = { function() starcraft.bind_buffer("e") end, "Bind Starcraft buffer 'e'" },
      ["f"] = { function() starcraft.bind_buffer("f") end, "Bind Starcraft buffer 'f'" },
      ["g"] = { function() starcraft.bind_buffer("g") end, "Bind Starcraft buffer 'g'" },
      ["h"] = { function() starcraft.bind_buffer("h") end, "Bind Starcraft buffer 'h'" },
      ["i"] = { function() starcraft.bind_buffer("i") end, "Bind Starcraft buffer 'i'" },
      ["j"] = { function() starcraft.bind_buffer("j") end, "Bind Starcraft buffer 'j'" },
      ["k"] = { function() starcraft.bind_buffer("k") end, "Bind Starcraft buffer 'k'" },
      ["l"] = { function() starcraft.bind_buffer("l") end, "Bind Starcraft buffer 'l'" },
      ["m"] = { function() starcraft.bind_buffer("m") end, "Bind Starcraft buffer 'm'" },
      ["n"] = { function() starcraft.bind_buffer("n") end, "Bind Starcraft buffer 'n'" },
      ["o"] = { function() starcraft.bind_buffer("o") end, "Bind Starcraft buffer 'o'" },
      ["p"] = { function() starcraft.bind_buffer("p") end, "Bind Starcraft buffer 'p'" },
      ["q"] = { function() starcraft.bind_buffer("q") end, "Bind Starcraft buffer 'q'" },
      ["r"] = { function() starcraft.bind_buffer("r") end, "Bind Starcraft buffer 'r'" },
      ["s"] = { function() starcraft.bind_buffer("s") end, "Bind Starcraft buffer 's'" },
      ["t"] = { function() starcraft.bind_buffer("t") end, "Bind Starcraft buffer 't'" },
      ["u"] = { function() starcraft.bind_buffer("u") end, "Bind Starcraft buffer 'u'" },
      ["v"] = { function() starcraft.bind_buffer("v") end, "Bind Starcraft buffer 'v'" },
      ["w"] = { function() starcraft.bind_buffer("w") end, "Bind Starcraft buffer 'w'" },
      ["x"] = { function() starcraft.bind_buffer("x") end, "Bind Starcraft buffer 'x'" },
      ["y"] = { function() starcraft.bind_buffer("y") end, "Bind Starcraft buffer 'y'" },
      ["z"] = { function() starcraft.bind_buffer("z") end, "Bind Starcraft buffer 'z'" },
    },
    ["'"] = {
      name = "Starcraft jump",
      ["<F1>"] = {function() starcraft.go_to_buffer("F1") end, "Go to Starcraft buffer F1"},
      ["<F2>"] = {function() starcraft.go_to_buffer("F2") end, "Go to Starcraft buffer F2"},
      ["<F3>"] = {function() starcraft.go_to_buffer("F3") end, "Go to Starcraft buffer F3"},
      ["<F4>"] = {function() starcraft.go_to_buffer("F4") end, "Go to Starcraft buffer F4"},
      ["<F5>"] = {function() starcraft.go_to_buffer("F5") end, "Go to Starcraft buffer F5"},
      ["<F6>"] = {function() starcraft.go_to_buffer("F6") end, "Go to Starcraft buffer F6"},
      ["<F7>"] = {function() starcraft.go_to_buffer("F7") end, "Go to Starcraft buffer F7"},
      ["<F8>"] = {function() starcraft.go_to_buffer("F8") end, "Go to Starcraft buffer F8"},
      ["<F9>"] = {function() starcraft.go_to_buffer("F9") end, "Go to Starcraft buffer F9"},
      ["<F10>"] = {function() starcraft.go_to_buffer("F10") end, "Go to Starcraft buffer F10"},
      ["<F11>"] = {function() starcraft.go_to_buffer("F11") end, "Go to Starcraft buffer F11"},
      ["<F12>"] = {function() starcraft.go_to_buffer("F12") end, "Go to Starcraft buffer F12"},
      ["1"] = {function() starcraft.go_to_buffer("1") end, "Go to Starcraft buffer #1"},
      ["2"] = {function() starcraft.go_to_buffer("2") end, "Go to Starcraft buffer #2"},
      ["3"] = {function() starcraft.go_to_buffer("3") end, "Go to Starcraft buffer #3"},
      ["4"] = {function() starcraft.go_to_buffer("4") end, "Go to Starcraft buffer #4"},
      ["5"] = {function() starcraft.go_to_buffer("5") end, "Go to Starcraft buffer #5"},
      ["6"] = {function() starcraft.go_to_buffer("6") end, "Go to Starcraft buffer #6"},
      ["7"] = {function() starcraft.go_to_buffer("7") end, "Go to Starcraft buffer #7"},
      ["8"] = {function() starcraft.go_to_buffer("8") end, "Go to Starcraft buffer #8"},
      ["9"] = {function() starcraft.go_to_buffer("9") end, "Go to Starcraft buffer #9"},
      ["0"] = {function() starcraft.go_to_buffer("0") end, "Go to Starcraft buffer #10"},
      ["a"] = {function() starcraft.go_to_buffer("a") end, "Go to Starcraft buffer 'a'"},
      ["b"] = {function() starcraft.go_to_buffer("b") end, "Go to Starcraft buffer 'b'"},
      ["c"] = {function() starcraft.go_to_buffer("c") end, "Go to Starcraft buffer 'c'"},
      ["d"] = {function() starcraft.go_to_buffer("d") end, "Go to Starcraft buffer 'd'"},
      ["e"] = {function() starcraft.go_to_buffer("e") end, "Go to Starcraft buffer 'e'"},
      ["f"] = {function() starcraft.go_to_buffer("f") end, "Go to Starcraft buffer 'f'"},
      ["g"] = {function() starcraft.go_to_buffer("g") end, "Go to Starcraft buffer 'g'"},
      ["h"] = {function() starcraft.go_to_buffer("h") end, "Go to Starcraft buffer 'h'"},
      ["i"] = {function() starcraft.go_to_buffer("i") end, "Go to Starcraft buffer 'i'"},
      ["j"] = {function() starcraft.go_to_buffer("j") end, "Go to Starcraft buffer 'j'"},
      ["k"] = {function() starcraft.go_to_buffer("k") end, "Go to Starcraft buffer 'k'"},
      ["l"] = {function() starcraft.go_to_buffer("l") end, "Go to Starcraft buffer 'l'"},
      ["m"] = {function() starcraft.go_to_buffer("m") end, "Go to Starcraft buffer 'm'"},
      ["n"] = {function() starcraft.go_to_buffer("n") end, "Go to Starcraft buffer 'n'"},
      ["o"] = {function() starcraft.go_to_buffer("o") end, "Go to Starcraft buffer 'o'"},
      ["p"] = {function() starcraft.go_to_buffer("p") end, "Go to Starcraft buffer 'p'"},
      ["q"] = {function() starcraft.go_to_buffer("q") end, "Go to Starcraft buffer 'q'"},
      ["r"] = {function() starcraft.go_to_buffer("r") end, "Go to Starcraft buffer 'r'"},
      ["s"] = {function() starcraft.go_to_buffer("s") end, "Go to Starcraft buffer 's'"},
      ["t"] = {function() starcraft.go_to_buffer("t") end, "Go to Starcraft buffer 't'"},
      ["u"] = {function() starcraft.go_to_buffer("u") end, "Go to Starcraft buffer 'u'"},
      ["v"] = {function() starcraft.go_to_buffer("v") end, "Go to Starcraft buffer 'v'"},
      ["w"] = {function() starcraft.go_to_buffer("w") end, "Go to Starcraft buffer 'w'"},
      ["x"] = {function() starcraft.go_to_buffer("x") end, "Go to Starcraft buffer 'x'"},
      ["y"] = {function() starcraft.go_to_buffer("y") end, "Go to Starcraft buffer 'y'"},
      ["z"] = {function() starcraft.go_to_buffer("z") end, "Go to Starcraft buffer 'z'"},
    },
    ["<F1>"] = {function() starcraft.go_to_buffer("F1") end, "Go to Starcraft buffer F1"},
    ["<F2>"] = {function() starcraft.go_to_buffer("F2") end, "Go to Starcraft buffer F2"},
    ["<F3>"] = {function() starcraft.go_to_buffer("F3") end, "Go to Starcraft buffer F3"},
    ["<F4>"] = {function() starcraft.go_to_buffer("F4") end, "Go to Starcraft buffer F4"},
    ["<F5>"] = {function() starcraft.go_to_buffer("F5") end, "Go to Starcraft buffer F5"},
    ["<F6>"] = {function() starcraft.go_to_buffer("F6") end, "Go to Starcraft buffer F6"},
    ["<F7>"] = {function() starcraft.go_to_buffer("F7") end, "Go to Starcraft buffer F7"},
    ["<F8>"] = {function() starcraft.go_to_buffer("F8") end, "Go to Starcraft buffer F8"},
    ["<F9>"] = {function() starcraft.go_to_buffer("F9") end, "Go to Starcraft buffer F9"},
    ["<F10>"] = {function() starcraft.go_to_buffer("F10") end, "Go to Starcraft buffer F10"},
    ["<F11>"] = {function() starcraft.go_to_buffer("F11") end, "Go to Starcraft buffer F11"},
    ["<F12>"] = {function() starcraft.go_to_buffer("F12") end, "Go to Starcraft buffer F12"},
  },
  {}
)
